/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OrphansRouteImport } from './routes/orphans'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrphansOrphanIdRouteImport } from './routes/orphans.$orphanId'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OrphansRoute = OrphansRouteImport.update({
  id: '/orphans',
  path: '/orphans',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrphansOrphanIdRoute = OrphansOrphanIdRouteImport.update({
  id: '/$orphanId',
  path: '/$orphanId',
  getParentRoute: () => OrphansRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/campaigns': typeof CampaignsRoute
  '/orphans': typeof OrphansRouteWithChildren
  '/profile': typeof ProfileRoute
  '/orphans/$orphanId': typeof OrphansOrphanIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/campaigns': typeof CampaignsRoute
  '/orphans': typeof OrphansRouteWithChildren
  '/profile': typeof ProfileRoute
  '/orphans/$orphanId': typeof OrphansOrphanIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/campaigns': typeof CampaignsRoute
  '/orphans': typeof OrphansRouteWithChildren
  '/profile': typeof ProfileRoute
  '/orphans/$orphanId': typeof OrphansOrphanIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/campaigns'
    | '/orphans'
    | '/profile'
    | '/orphans/$orphanId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/campaigns'
    | '/orphans'
    | '/profile'
    | '/orphans/$orphanId'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/campaigns'
    | '/orphans'
    | '/profile'
    | '/orphans/$orphanId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  CampaignsRoute: typeof CampaignsRoute
  OrphansRoute: typeof OrphansRouteWithChildren
  ProfileRoute: typeof ProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orphans': {
      id: '/orphans'
      path: '/orphans'
      fullPath: '/orphans'
      preLoaderRoute: typeof OrphansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orphans/$orphanId': {
      id: '/orphans/$orphanId'
      path: '/$orphanId'
      fullPath: '/orphans/$orphanId'
      preLoaderRoute: typeof OrphansOrphanIdRouteImport
      parentRoute: typeof OrphansRoute
    }
  }
}

interface OrphansRouteChildren {
  OrphansOrphanIdRoute: typeof OrphansOrphanIdRoute
}

const OrphansRouteChildren: OrphansRouteChildren = {
  OrphansOrphanIdRoute: OrphansOrphanIdRoute,
}

const OrphansRouteWithChildren =
  OrphansRoute._addFileChildren(OrphansRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  CampaignsRoute: CampaignsRoute,
  OrphansRoute: OrphansRouteWithChildren,
  ProfileRoute: ProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
